language: node_js
node_js:
- 8.10
jobs:
  include:
    - stage: d1🚀
      script: npm test
    - stage: d2🚀
      if: branch = feature/documentation
      script: npm test
    - stage: test🚀
      if: branch = test
      before_script: npm test
      script: ./ci-build.sh
