language: node_js
node_js:
- 8.10
script: ./ci-build.sh
# Try to do this with a npm script instead, because this deploys per function
#deploy:
#  # TEST
#  - provider: lambda
#    function_name: "staticSiteMailer"
#    region: "eu-west-1"
#    role: "arn:aws:iam::552504168047:role/codestar-nl-serverless-test-eu-west-1-lambdaRole"
#    runtime: "nodejs8.10"
#    handler_name: "serverless/mailer.staticSiteMailer"
#    on:
#      branch: test
#  - provider: lambda
#    function_name: "getUpcomingEvents"
#    region: "eu-west-1"
#    role: "arn:aws:iam::552504168047:role/codestar-nl-serverless-test-eu-west-1-lambdaRole"
#    runtime: "nodejs8.10"
#    handler_name: "serverless/meetup.getUpcomingEvents"
#    on:
#      branch: test
#  # PROD
#  - provider: lambda
#    stage: prod
##    function_name: "lambda-test"
##    region: "us-east-1"
##    role: "arn:aws:iam::0123456789012:role/lambda_basic_execution"
##    runtime: "nodejs8.10"
##    handler_name: "handler"
#    on:
#      branch: production